version: "3.9"
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  profile-service:
    image: driver-module/profile-service:latest
    ports:
      - "8080:8080"
    depends_on:
      - mongo
volumes:
  mongo_data:
    driver: local
