version: "3.9"
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    networks:
      - bridge-network
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  profile-service:
    image: driver-module/profile-service:latest
    container_name: profile-service
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - bridge-network
  document-service:
    image: driver-module/document-service:latest
    container_name: document-service
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    networks:
      - bridge-network
volumes:
  mongo_data:
    driver: local
networks:
  bridge-network:
    driver: bridge
